name: Integracao Continua

on:
    push: 
        branches:
            [ "*" ]

    pull_request:
        branches:
            [ "*" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
        - uses: actions/checkout@v4.2.2
        - uses: actions/setup-node@v4.1.0 
          with:
            node-version: '22.12.0'
        - run: npm install 
        - run: npm test


